name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    # Step 4: Run tests
    - name: Run tests
      run: pytest --maxfail=5 --disable-warnings

    # Step 5: Run Black formatter check
    - name: Check code formatting with Black
      run: black --check .

    # Step 6: Upload performance report
    - name: Upload performance report
      if: success()  # Upload only if previous steps succeed
      uses: actions/upload-artifact@v3
      with:
        name: performance-report
        path: performance_report.txt